image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

build:
  stage: build
  script:
#    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest
  only:
    - main
